### ISSUE TITLE
Fix social links in footer

### ISSUE THREAD

**Issue by tedyw** [osqledaren/web1617#26]
Icon buttons are not doing anything right now. We also need to use the correct icons corresponding to the social media networks we currently are using more frequently (Facebook and Instagram).

**Comment by tedyw** [comment]
Made some changes to the footer. Navigation links have been modified to match the app header. Copyright notice have been added. Removed social media icons not used while keeping facebook, adding instragram and github. These still need to be linked.

**Comment by emmabckstrm** [comment]
Icons are now linked!
