### ISSUE TITLE
Branches (App-podcast and App-play) can’t automatically merge with master branch.

### ISSUE THREAD

**Issue by AZNanoi** [osqledaren/web1617#29]
It seems like file structure in App-podcast and App-play is different from master. In order to fix this issue, files regarding podcast/play must be moved to new branch adopted from master, respectively.

**Comment by tedyw** [comment]
Have you tried merging origin/master into your local branch?

**Comment by AZNanoi** [comment]
So much conflicts! I have solved the problems in easy way by creating new branches "App-podcast-new" and "App-play-new". 77d9aa758d9647d6d910a246eaea9cded532bd4f
f4bad9297fc52a2f8fcb40ef7996e447b0e6ab83
