### ISSUE TITLE
Missing element: Search bar is missing on some pages

### ISSUE THREAD

**Issue by emmabckstrm** [osqledaren/web1617#40]
The search bar is currently only present on the home and about pages (in the menu)

**Comment by tedyw** [comment]
Well observed. It has been added as a feature that each route can activate a certain search archive depending on content that is requested on the page, e.g on the news page the search will be performed on news, on the pod page search will be performed on pods. I've forgotten to activate this on the missing pages (look in onInit inside the component logic)
