### ISSUE TITLE
Update advertising page to match new layout

### ISSUE THREAD

**Issue by tedyw** [osqledaren/web1617#48]

**Comment by AZNanoi** [comment]
Fixed the UTGIVNINGSPLAN illustration and implemented responsive layout for advertisement page.
fe8a53dc11720305cfebc31af2d07c27bc5ada3e

**Comment by AZNanoi** [comment]
Updated advertising page to match new layout.
Fixed SVG illustration issue with Safari.
Adjusted layout for small screens. f01ae3eb7f69a5529a7cb4818001de126831371f
