### ISSUE TITLE
Missing printed issues page

### ISSUE THREAD

**Issue by tedyw** [osqledaren/web1617#8]
The printed issues page showcases all existing printed issues.

**Comment by AZNanoi** [comment]
What do you mean by "printed issues page"?

**Comment by tedyw** [comment]
Check this 7324e1b

**Comment by AZNanoi** [comment]
Aha ok, let me check it out then.

**Comment by AZNanoi** [comment]
Added printed-issues page 6a0abf143648fb59c234f9515698b9401618b7eb

**Comment by tedyw** [comment]
Check that the latest printed issues are included @emmabckstrm and @simpison. If there is time, implement automatic retrieval, otherwise put it to the backlog by saving it as a future issue.

**Comment by tedyw** [comment]
Did some minor layout adjustments. The issues presented are however not correct (look in 16/17). Every issue  haven't been released yet. Placeholders needs to be added.

**Comment by emmabckstrm** [comment]
Placeholders added. Also restructured the code a bit, new reusable printed-issues-grid-component. Takes data from array in printed-issues, can be rebuilt into retrieving data automatically
